[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/api/*"
  [headers.values]
  Access-Control-Allow-Origin = "https://front-meetout.vercel.app"
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
